# Ejecicios Lecciones 6-8

In [301]:
import numpy as np

### Ejercicio 1
Usando el array que encontráis a continuación.

- ¿Hay algún valor múltiplo de 7?
- Devuelve un array con todos los nº menores de 40 o que sean múltiplos de 7

In [303]:
a = np.array([2, 5, 4, 2, 49, 34, 59, 21, 45, 6, 105])
#calcular si algún valor es multiplo de 7
np.any( a % 7) == 0
#devolver un array con numeros menos de 40 o multiplos de 7
#necesitamos la funcion logical_or()
np.logical_or(a<40, a % 7 == 0)

array([ True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True])

In [304]:
result = a[np.logical_or(a<40, a % 7 == 0)]


### Ejercicio 2

Usando el array resultado del ejercicio anterior, calcula:

- El producto de todos sus valores
- Convierte el array el una matriz 3x3 y realiza la suma por filas
- Calcula el log10 de cada elemento de la matriz que acabas de crear

In [306]:
#calcular el producto de todos sus valores
producto = np.prod(result)
print("El producto de todos sus valores es:",producto)

El producto de todos sus valores es: 1763294400


In [307]:
# Convierte el array el una matriz 3x3 y realiza la suma por filas
matriz_result = result.reshape(3,3)
print("matriz de 3x3 del array: \n", matriz_result)
resultado_suma_filas = np.sum(matriz_result, axis = 1)
print("\n resultado de la suma por filas: ",resultado_suma_filas)

matriz de 3x3 del array: 
 [[  2   5   4]
 [  2  49  34]
 [ 21   6 105]]

 resultado de la suma por filas:  [ 11  85 132]


In [308]:
# Calcula el log10 de cada elemento de la matriz que acabas de crear
np.log10(matriz_result)

array([[0.30103   , 0.69897   , 0.60205999],
       [0.30103   , 1.69019608, 1.53147892],
       [1.32221929, 0.77815125, 2.0211893 ]])

### Ejercicio 3

Haciendo uso de la matriz 3x3 creada en el ejercicio anterior y del siguiente array a, calcule:

- La suma de la matriz más el vector
- La división de ambos. ¿qué ocurre? Modifique el valor extraño por 0.
- El valor máximo de la matriz resultado de la división. ¿y por filas? ¿y por columnas?

In [310]:
a = np.array([0,3,5])

In [311]:
# suma de la matriz más el vector
np.add(matriz_result, a)

array([[  2,   8,   9],
       [  2,  52,  39],
       [ 21,   9, 110]])

In [312]:
#división de ambos. ¿qué ocurre? 
result_division = np.divide(matriz_result , a)
#en alfunos casos vemos que el resultado de la operación es infinito
print(result_division)

[[        inf  1.66666667  0.8       ]
 [        inf 16.33333333  6.8       ]
 [        inf  2.         21.        ]]


C:\Users\nuria\AppData\Local\Temp\ipykernel_1744\3807235382.py:2: RuntimeWarning: divide by zero encountered in divide
  result_division = np.divide(matriz_result , a)


In [313]:
#Modifique el valor extraño por 0.
result_division[np.isinf(result_division)] = 0

In [314]:
# El valor máximo de la matriz resultado de la división. ¿y por filas? ¿y por columnas?
np.max(result_division)

21.0

In [315]:
#El valor máximo de la matriz resultado de la división por filas 
np.max(result_division, axis = 0)

array([ 0.        , 16.33333333, 21.        ])

In [316]:
#El valor máximo de la matriz resultado de la división por columnas
np.max(result_division, axis = 1)


array([ 1.66666667, 16.33333333, 21.        ])

### Ejercicio 4

In [318]:
array = np.array([44, 28,  8, 34, 34, 26, 32, 12, 28,  6, 19, 12, 46, 20, 20, 49, 18,
       19, 15, 15, 43,  3, 17, 33, 27, 10, 18,  2,  3,  3, 35, 35, 21, 17,
       36, 31, 16, 27,  6, 46, 29, 25, 26, 48, 30, 19, 18,  1, 43, 10, 32,
       15, 32, 30, 40, 41, 11, 46, 39,  5, 40,  1, 26, 10, 18, 26, 25, 25,
       21, 30, 12, 46,  1, 43,  1,  3, 26, 24,  0, 36, 34,  7, 26, 25, 41,
       22,  1, 16, 43,  1, 46, 14, 17, 39, 12,  9, 42, 48,  9, 45, 47, 32,
       15,  6, 40, 18,  6, 13, 35,  8, 46, 48, 26, 23, 12, 29, 21,  6,  3,
       22, 27, 16, 27, 10, 28, 23,  5, 24, 17, 43, 25, 11, 38, 40, 32, 42,
       27, 32,  6, 16, 18, 10, 18, 34, 34,  3,  4,  5,  4,  0, 35, 30,  9,
       16, 32, 46,  7, 10, 20, 13, 48,  8, 27, 27, 27, 16, 17, 12, 35, 31,
       21, 29, 15, 49, 14, 22, 18,  0, 13, 14, 39, 30,  4, 48,  1, 19, 33,
       39,  9,  0, 24,  6, 12, 24, 29, 16, 11, 12, 13, 11])

array

array([44, 28,  8, 34, 34, 26, 32, 12, 28,  6, 19, 12, 46, 20, 20, 49, 18,
       19, 15, 15, 43,  3, 17, 33, 27, 10, 18,  2,  3,  3, 35, 35, 21, 17,
       36, 31, 16, 27,  6, 46, 29, 25, 26, 48, 30, 19, 18,  1, 43, 10, 32,
       15, 32, 30, 40, 41, 11, 46, 39,  5, 40,  1, 26, 10, 18, 26, 25, 25,
       21, 30, 12, 46,  1, 43,  1,  3, 26, 24,  0, 36, 34,  7, 26, 25, 41,
       22,  1, 16, 43,  1, 46, 14, 17, 39, 12,  9, 42, 48,  9, 45, 47, 32,
       15,  6, 40, 18,  6, 13, 35,  8, 46, 48, 26, 23, 12, 29, 21,  6,  3,
       22, 27, 16, 27, 10, 28, 23,  5, 24, 17, 43, 25, 11, 38, 40, 32, 42,
       27, 32,  6, 16, 18, 10, 18, 34, 34,  3,  4,  5,  4,  0, 35, 30,  9,
       16, 32, 46,  7, 10, 20, 13, 48,  8, 27, 27, 27, 16, 17, 12, 35, 31,
       21, 29, 15, 49, 14, 22, 18,  0, 13, 14, 39, 30,  4, 48,  1, 19, 33,
       39,  9,  0, 24,  6, 12, 24, 29, 16, 11, 12, 13, 11])

Considerando el array de números que podéis encontrar justo arriba, calcula:

- Valor medio y mediano
- ¿Qué valor se encuentra en el tercer cuártil?
- ¿Qué valor se encuentra en el percentil 25? ¿y en el 50? ¿con qué valor coincide este último?
- ¿Cuál es la desviación estándar y la varianza del conjunto de datos?

In [320]:
# Valor medio y mediano
#El valor medio
mean = np.mean(array)
print(mean)
#La mediana es el valor central. Si el array tiene un número de elementos impar, la mediana se calcula como la media de los dos valores centrales
median = np.median(array)
print(median)

22.405
21.0


In [321]:

# ¿Qué valor se encuentra en el tercer cuártil?
np.quantile(array, 0.5)

21.0

In [322]:
# ¿Qué valor se encuentra en el percentil 25? ¿y en el 50? ¿con qué valor coincide este último?
percentil_25 = np.percentile(array, 25)
percentil_50 = np.percentile(array, 50)
print(f"  El resultado del percentil 25 es: {percentil_25} \n El resultado del percentil 50 es: {percentil_50}, este último coincide con el resultado de la mediana: {median}")

  El resultado del percentil 25 es: 11.75 
 El resultado del percentil 50 es: 21.0, este último coincide con el resultado de la mediana: 21.0


In [323]:
# ¿Cuál es la desviación estándar y la varianza del conjunto de datos?
desviacion_estandard= np.std(array)
varianza = np.var(array)
#Comprobamos la varianza
comprobacion_varianza= np.sqrt(186.85097500000003)
print(f"Desviancion estandard: {desviacion_estandard}, \n varianza : {varianza}, \n comprobacion varianza: {comprobacion_varianza}" )

Desviancion estandard: 13.66934435150421, 
 varianza : 186.85097500000003, 
 comprobacion varianza: 13.66934435150421
