# Ejercicios Lecciones 1-5


### Ejecicio 1

Genera un array que contenga 25 ekenebtis entre 0 y 99 siguiendo una distribución lineal. Luego,
transforma ese array en una matriz de 5x5 ¿Cuál es la diafonal de la matriz?
¿Y la diagonal justo superior?

In [164]:
import numpy as np

In [166]:
array = np.linspace(start=0, stop= 100, num=25, endpoint =False)
array

array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44., 48.,
       52., 56., 60., 64., 68., 72., 76., 80., 84., 88., 92., 96.])

In [168]:
matriz = array.reshape(5,5)
diag = np.diag(matriz)
diag_superior = np.diag(matriz,k=1)
print("la diagonal de la matriz es", diag)
print("la diagonal superior es", diag_superior)

la diagonal de la matriz es [ 0. 24. 48. 72. 96.]
la diagonal superior es [ 4. 28. 52. 76.]


### Ejercicio 2

Crea un de 5 x 4 con el valor repetido 10. Une esa matriz a la matriz del ejercicio anterior para conseguir nuevas matrices una de 5x9, y otra de 9x 5

In [172]:
#creamos la matriz en la que el valor 5 se repite 20 veces, y cambiamos su form a 4 filas 5 columnas
matriz2 = np.repeat(a = 5, repeats=20).reshape(4,5)
#concatenamos las matrices
#para que me de una matriz de 5x9 tengo que concantenar por columna , por axis = 1
#antes de concatenar tengo que transponer la matriz2
np.concatenate((matriz,matriz2.T), axis = 1)

array([[ 0.,  4.,  8., 12., 16.,  5.,  5.,  5.,  5.],
       [20., 24., 28., 32., 36.,  5.,  5.,  5.,  5.],
       [40., 44., 48., 52., 56.,  5.,  5.,  5.,  5.],
       [60., 64., 68., 72., 76.,  5.,  5.,  5.,  5.],
       [80., 84., 88., 92., 96.,  5.,  5.,  5.,  5.]])

### Ejercicio 3

Teniendo el array inicial que podéis ver justo abajo, debéis realizar las operaciones necesarias para obtener el array:

array(['Este', 'Es', 'Un', 'Curso', 'De', 'Openwebinars'], dtype='<U12')

¿Qué elementos del array comienzan por 'E'?



In [177]:
a = np.array(['     este es un curso de openwebinars    '])
array = np.char.strip(a)
#separamos la cadena en elementos del array
array2= np.char.split(array, sep= ' ')
array2= np.array(array2[0])
#ponemosque empiecen por mayuscula los elementos del array
array3 = np.char.capitalize(array2)
array3
starts_with_E= np.char.startswith(array3,'E')

In [179]:
print("elementos que empiezan por E: ",array3[starts_with_E])

elementos que empiezan por E:  ['Este' 'Es']


### Ejercicio 4

Considerando las matrices A y B. 

$A = \begin{pmatrix}
3 & 1 & 2 \\
4 & 1 & 3 \\
2 & 0 & 1
\end{pmatrix}$
$B = \begin{pmatrix}
2 & 0 & 3 \\
1 & 1 & 1 \\
0 & 2 & 4
\end{pmatrix}$

- Realiza la multiplicación matricial de AxB y BxA. ¿Son iguales?
- Realiza la multiplicación de la matriz A x 2
- ¿Cúanto es la multiplicación escalar de AxB? ¿y de BxA?

In [183]:
a = np.array([[3,1,2], [4,1,3], [2,0,1]])
b = np.array([[2,0,3], [1,1,1], [0,2,4]])

print(a)
print(b)

[[3 1 2]
 [4 1 3]
 [2 0 1]]
[[2 0 3]
 [1 1 1]
 [0 2 4]]


In [185]:
#multiplicacion axb
axb = np.dot(a,b)
print("axb",axb)
#multiplicacion bxa
bxa = np.dot(b,a)
print("bxa",bxa)
print("No son iguales")

axb [[ 7  5 18]
 [ 9  7 25]
 [ 4  2 10]]
bxa [[12  2  7]
 [ 9  2  6]
 [16  2 10]]
No son iguales


In [187]:
#Realiza la multiplicacion de la matriz A x 2
ax2 = a*2
print(ax2)

[[6 2 4]
 [8 2 6]
 [4 0 2]]


In [189]:
#¿Cúanto es la multiplicación escalar de AxB? ¿y de BxA?
#Para realizar la multiplicacion escalar empleamos .vdot
np.vdot(a,b)

24

In [191]:
np.vdot(b,a)

24

### Ejercicio 5

Usando la matriz A del ejercicio anterior, calcula:

- A^3
- El determinante de A
- Resuelve la ecuación Ax = y, siendo y el array [3,2,5]

In [195]:
a

array([[3, 1, 2],
       [4, 1, 3],
       [2, 0, 1]])

In [197]:
b

array([[2, 0, 3],
       [1, 1, 1],
       [0, 2, 4]])

In [199]:
# A^3
a3 = np.linalg.matrix_power(a, 3)
a3

array([[ 89,  21,  57],
       [114,  27,  73],
       [ 42,  10,  27]])

In [201]:
#El determinante de A
np.linalg.det(a)

1.0

In [210]:
#- Resuelve la ecuación Ax = y, siendo y el array [3,2,5]
#creamos el array
y = np.array([3,2,5])
#El metodo linal.solv nos permite resvlver ecuaciones lineanes
#pasamos a linalg.solv, la matriz y el array
np.linalg.solve(a, y)

array([ 6., -1., -7.])