# Manipulacion arrays

### Dimensiones del array

In [58]:
import numpy as np
a = np.array([[1,2,3,4],[4,3,2,1]])
a.shape #nos dice la forma del array

(2, 4)

In [59]:
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [60]:
a.reshape((4,2)) #reshape - modificamos la forma del array 

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [77]:
#ravel - transforma un array multimidimensional en uno unidimensional
a.ravel()


array([1, 2, 3, 4, 4, 3, 2, 1])

In [73]:
a.T #opcion de traansponer el array

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

### Tipos de arrays

In [ ]:
#asarray - Convierte una lista python en un array
np.asarray([1,2,3,4], dtype = np.int8)

#asfarray - convierte la lista en un array de floats
np.asfarray([1,2,3,4])

In [ ]:
a = [1,2,3,4,nan]
no.asarray.chkfinite(a) #comprueba que no haya infinitos ni nan

In [ ]:
#Puedo decirle las veces que quiero que se repita un numero y despues darle forma al array
np.repeat(a = 99, repeats = 10).reshape((2,5))

In [ ]:
# concatenate - Une un conjunto de arrays por filas o columnas

a = np.array([[1,2,3,4], [1,2,3,4]])
b = np.array([[4,3,2,1]])

print(a.shape)
print(b.shape)

#axis= 0, significa a nivel de fila
#axis=1, significa a nivel de columnas
np.concatenate(a,b),axis = 0)
#tengo que aplicar el tranposse de a y de b antes de concatenar los arrays a nivel de coluumna
np.concatenate((a.T,b.T), axis = 1)

In [83]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
#stack - rambien permite concatenar arrays
np.stack((a,b), axis = 1)

array([[1, 4],
       [2, 3],
       [3, 2],
       [4, 1]])

### Division de arrays

In [91]:
#genero un array conn valores de 0 a 19
a = np.arange(0, 20)
#dividimos el array en 4 secciones
np.split(a, indices_or_sections=4)
#también puedo dividir por los rangos que yo elija
np.split(a, [3, 5, 10, 16])


[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19])]

### Añadir y eliminar los elementos de un array

In [93]:
# insert - Inserta elementos en una posicion del array
#obj -  indica la posicion en la que los valores son inserador
a = np.array([1,2,3,4])
np.insert(a, obj=4, values=[5,6])
#append - añade un valor al fila de la lista
np.append(a, [5,6])
#delete - elimina un valor en la posicion indicada
#obj - indica la posicion
np.delete(a, obj = 3)

array([1, 2, 3, 4, 5, 6])

In [97]:
#trim_zeros elimina los zeros del principio y del  final
a = np.array([0, 0, 0, 0, 1, 2, 3, 4, 0, 0])
np.trim_zeros(a)

array([1, 2, 3, 4])

In [ ]:
#unique - me devuelve solo lo valores unicos
a = np.array([1,1,1,1,2,2,2,2,3,3,3,3])
np.unique(a)

array([1, 2, 3])

# Cadenas

In [114]:
# add - Devuelve la concatenación de cadenas de elementos para dos matrices de str o unicode.
a = np.array(['A', 'B', 'C'], dtype = str)
b = np.array(['D', 'E', 'F'], dtype = str)
#pasamos al metodo add las cadenas que queremos concatenar en el orden que queremos concatenarlas
np.char.add(a,b)

array(['AD', 'BE', 'CF'], dtype='<U2')

In [ ]:
# multiply - Devuelve (a * i), es decir, concatenación múltiple de cadenas, por elementos.
#es decir multiplicara el primer elemento * 2 (a*2)), el segundo * 3 (b*3)y el tercero *4 (c*4)
np.char.multiply(a, [2,3,4])