# Rutinas de Creación

In [86]:
import numpy as np
np.eye(4) #evuele una matriz que en la diagonal devuelve unos y el resto son zeros 
#el parámetro k nos permite desplazar la diagonal, desplazar el uno
np.eye(4, k = -1) 

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [87]:
#similar a np.eye pero el 1 no se puede desplazar
np.identity(4,dtype = 'int8')
#nos permite rellenar la matriz con el valor que queramos, en este caso el numero 99
np.full(shape=(4,4), fill_value= 99)
#puede ser rellenado también conuna lista
np.full(shape=(4,4), fill_value= [10,20,30,40])

array([[10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40],
       [10, 20, 30, 40]])

In [88]:
### Creación desde datos existentes

In [89]:
np.fromstring('1 2 3 4',sep = ' ') #puedo pasarle un string diciendo cual es el separador, en este caso caracter vacio/espacio, y se genera un array

array([1., 2., 3., 4.])

In [90]:
import os
cwd = os.getcwd()
print(cwd)
datos = np.loadtxt('./datos.txt', delimiter=' ', usecols=(0, 1, 2, 3))  # Adjust indices as needed
print(datos)

C:\Users\nuria\Numpy
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [91]:
### Rangos numéricos

In [92]:
np.arange(0,10,2)
#el Linspace recibe el valor inicial, valor final, y numero de elementos
np.linspace(start=1,stop=10,num=5)
np.linspace(start=1,stop=10,num=5, endpoint=False, retstep=True)

(array([1. , 2.8, 4.6, 6.4, 8.2]), 1.8)

In [93]:

# logspace - Igual que el linspace pero aplicando una escala logaritmica
np.logspace(start=2, stop= 3.5, num = 10)

array([ 100.        ,  146.77992676,  215.443469  ,  316.22776602,
        464.15888336,  681.29206906, 1000.        , 1467.79926762,
       2154.43469003, 3162.27766017])

In [94]:
# Creación de matrices

In [111]:
a = np.eye(N=4) #creamos matriz
np.diag(a) #le pido que me devuelva la diagona de la matriz
np.diag(a,k=1) #puedo pedir la diagonal deplazada, aqui le pido la diagona " por encima"

#los valores de la diagonal se corresponden con V
#al igual que antes k me dice donde se situa la diagonal
np.diagflat(v=[1,2,3,4,5], k = 0)

#crea una matriz de una dimension N x M
#y pone unos en la diagonal y debajo de ella, y el resto lo rellena con el valor 0
np.tri(N=5,M=5)


array([[0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0]])