# Creacion de arrays en Numpy
- Un array es un elemento multidimentional que va a estar formado por una fila, por una columna o por ambas,
  esto lo convertiria en una matris

In [63]:
array1 = np.array([1,2,3,4,5,6], dtype='int')
array1
type(array1)

numpy.ndarray

In [64]:
array1.dtype

dtype('int32')

In [65]:
#creacion de un array de dos dimensiones
array2=np.array([[1,2,3],[4,5,6]],dtype='int',ndmin = 2)

In [66]:
#podemos crear un array de tipo complex
array3 = np.array([1,2,3], dtype= 'complex')
array3

array([1.+0.j, 2.+0.j, 3.+0.j])

In [67]:
# np.zeros, genera un array de ceros
np.zeros(10)

#np.ones
np.ones([5,2])

#genera una lista con un rango de numeros del 0 al 10(sin incluir el 10)
a = np.arange(0,10)
print(a)

#cambiamos la forma del array, pasamos de 1 dimension a 2 
a.reshape((2,5))


[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Tipos de datos en Numpy

In [69]:
#Importamos libreria de numpy
import numpy as np

- En numpy hay 24 nuevos tipos de datos comparado con python


In [71]:
#Puedo generar un arrary de 1 y 0 y decir que sea de tipo boolean
bool_array = np.array([[1,0,0,1],[0,1,1,0]], dtype=bool)
bool_array

array([[ True, False, False,  True],
       [False,  True,  True, False]])

In [72]:
char_array = np.array(['a','b','c'], dtype=np.chararray)
char_array

array(['a', 'b', 'c'], dtype=object)

- En numpy los tipos de datos tienen distintos tamaños
- Esto es relevante especialmente cuando manejamos grandes volúmenes de datos

In [97]:
from  sys import getsizeof

a = np.array([1, 2, 3, 4], dtype=np.int8)
b = np.array([1, 2, 3, 4], dtype=np.int64)

print("A", getsizeof(a))
print("B", getsizeof(b))

A 116
B 144


In [87]:
a.dtype

dtype('int32')