# Creacion de arrays en Numpy
- Un array es un elemento multidimentional que va a estar formado por una fila, por una columna o por ambas,
  esto lo convertiria en una matris

In [3]:
import numpy as np
array1 = np.array([1,2,3,4,5,6], dtype='int')
array1
type(array1)

numpy.ndarray

In [4]:
array1.dtype

dtype('int32')

In [5]:
#creacion de un array de dos dimensiones
array2=np.array([[1,2,3],[4,5,6]],dtype='int',ndmin = 2)

In [6]:
#podemos crear un array de tipo complex
array3 = np.array([1,2,3], dtype= 'complex')
array3

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
# np.zeros, genera un array de ceros
np.zeros(10)

#np.ones
np.ones([5,2])

#genera una lista con un rango de numeros del 0 al 10(sin incluir el 10)
a = np.arange(0,10)
print(a)

#cambiamos la forma del array, pasamos de 1 dimension a 2 
a.reshape((2,5))


[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Tipos de datos en Numpy

In [9]:
#Importamos libreria de numpy
import numpy as np

- En numpy hay 24 nuevos tipos de datos comparado con python


In [11]:
#Puedo generar un arrary de 1 y 0 y decir que sea de tipo boolean
bool_array = np.array([[1,0,0,1],[0,1,1,0]], dtype=bool)
bool_array

array([[ True, False, False,  True],
       [False,  True,  True, False]])

In [12]:
char_array = np.array(['a','b','c'], dtype=np.chararray)
char_array

array(['a', 'b', 'c'], dtype=object)

- En numpy los tipos de datos tienen distintos tamaños
- Esto es relevante especialmente cuando manejamos grandes volúmenes de datos

In [14]:
from  sys import getsizeof

a = np.array([1, 2, 3, 4], dtype=np.int8)
b = np.array([1, 2, 3, 4], dtype=np.int64)

print("A", getsizeof(a))
print("B", getsizeof(b))

A 116
B 144


In [15]:
a.dtype

dtype('int8')

# Constantes

In [17]:
np.inf #valor infinito

inf

In [18]:
np.NINF #valor infinito negativo

-inf

In [19]:
np.isinf(np.inf) #pregunto si un valor es infinito o no

True

In [20]:
np.isposinf(np.inf) #pregunto si es un positivo positivo

True

In [21]:
np.nan #nan = not a number

nan

In [22]:
np.PZERO 
np.NZERO

-0.0

In [23]:
np.e #contante para el numero e

2.718281828459045

In [24]:
np.pi #constante de pi

3.141592653589793

In [25]:
np.isfinite(np.e) #constante para saber si un numero es finito o no

True

# Mascaras

In [27]:
import numpy as np
import numpy.ma as ma #esta es la libreria que posee las funciones para poder trabajar con las máscaras
x = np.array([1,2,3,-1,4])
#Los 0 y 1 equivaldran a false y true
#Cuando el elemento de la máscara sea false es cuando vamos a considerar válido el elemento
#Cuando el elemento de la mascara sea true sera NO valido
mask_array = ma.masked_array(x , mask = [0,0,0,1,0])
mask_array.min() #preguntamos por el min, y omitira el -1 (esta oculto en la mascara)


1

In [28]:

#podemos preguntar si un elemento esta enmascarado
mask_array[3]is ma.masked

True